import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function Privacy() {
  return (
    <div className="min-h-screen bg-background text-foreground p-6 md:p-12">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="mb-8 flex items-center gap-4">
          <Link href="/">
            <Button variant="ghost" size="icon" className="rounded-full">
              <ArrowLeft className="w-4 h-4" />
            </Button>
          </Link>
          <h1 className="text-4xl font-serif text-gold">Privacy Policy</h1>
        </div>

        {/* Content */}
        <div className="space-y-6 text-foreground/80">
          <p className="text-sm leading-relaxed text-gold/80">
            We respect your privacy. This application is designed to avoid collecting personal data whenever possible.
          </p>

          <section className="space-y-3 pt-4 border-t border-border">
            <h2 className="text-xl font-serif text-gold">1. Information Collected</h2>
            <ul className="space-y-2 ml-4 list-disc list-inside text-sm">
              <li>This app does not collect names, emails, birth details, or identifying information</li>
              <li>Basic non-personal technical logs may be automatically generated by your browser or hosting service</li>
              <li>Location data is only used locally for astronomical calculations (not stored or transmitted)</li>
            </ul>
          </section>

          <section className="space-y-3 pt-4 border-t border-border">
            <h2 className="text-xl font-serif text-gold">2. Use of Information</h2>
            <p className="text-sm leading-relaxed">
              Any non-personal analytics data is used solely to improve performance, stability, and user experience.
            </p>
          </section>

          <section className="space-y-3 pt-4 border-t border-border">
            <h2 className="text-xl font-serif text-gold">3. Cookies & Local Storage</h2>
            <p className="text-sm leading-relaxed">
              The app may use local storage for saving your preferences such as:
            </p>
            <ul className="space-y-1 ml-4 list-disc list-inside text-sm">
              <li>Theme preference (light/dark mode)</li>
              <li>Language settings</li>
              <li>Other non-identifying user preferences</li>
            </ul>
            <p className="text-sm leading-relaxed pt-2">
              <span className="font-semibold">No tracking cookies or advertising cookies are used.</span>
            </p>
          </section>

          <section className="space-y-3 pt-4 border-t border-border">
            <h2 className="text-xl font-serif text-gold">4. Third-Party Services</h2>
            <p className="text-sm leading-relaxed">
              If any third-party service (e.g., hosting provider or embedded library) collects data, their own privacy policies apply.
            </p>
          </section>

          <section className="space-y-3 pt-4 border-t border-border">
            <h2 className="text-xl font-serif text-gold">5. Data Sharing</h2>
            <p className="text-sm leading-relaxed font-semibold text-gold">
              No user data is sold, shared, or transferred to any external party.
            </p>
          </section>

          <section className="space-y-3 pt-4 border-t border-border">
            <h2 className="text-xl font-serif text-gold">6. Security</h2>
            <p className="text-sm leading-relaxed">
              Reasonable measures are taken to protect the integrity of the application. However, no system is completely immune from risk.
            </p>
          </section>

          <section className="space-y-3 pt-4 border-t border-border">
            <h2 className="text-xl font-serif text-gold">7. Children's Privacy</h2>
            <p className="text-sm leading-relaxed">
              This application is suitable for general audiences but should be used with parental guidance for minors under 13.
            </p>
          </section>

          <section className="space-y-3 pt-4 border-t border-border">
            <h2 className="text-xl font-serif text-gold">8. Contact</h2>
            <p className="text-sm leading-relaxed">
              For questions or concerns about privacy, users may reach out via the support link on the website.
            </p>
          </section>
        </div>

        {/* Links */}
        <div className="mt-12 pt-8 border-t border-border flex flex-wrap gap-4 text-sm">
          <Link href="/legal">
            <Button variant="link" className="text-primary">Legal Disclaimer →</Button>
          </Link>
          <Link href="/terms">
            <Button variant="link" className="text-primary">Terms of Use →</Button>
          </Link>
        </div>
      </div>
    </div>
  );
}
